FROM fduarte42/docker-php:7.4
ARG TARGETARCH

# add ioncube_loader extension
COPY extension/ioncube_loaders_lin_*.tar.gz /tmp/

COPY add-ioncube_loader.sh /add-ioncube_loader.sh
RUN bash /add-ioncube_loader.sh && rm /add-ioncube_loader.sh

RUN rm /tmp/ioncube_loaders_lin_*.tar.gz
