#!/usr/bin/env bash

if [ -e "/ssh/id_rsa.pub" ]; then
    cp /ssh/id_rsa.pub /root/.ssh/id_rsa.pub
    chown -R root:root /root/.ssh/id_rsa.pub
    chmod 644 /root/.ssh/id_rsa.pub

    cp /ssh/id_rsa.pub /var/www/.ssh/id_rsa.pub
    chown -R www-data:www-data /var/www/.ssh/id_rsa.pub
    chmod 644 /var/www/.ssh/id_rsa.pub
fi

if [ -e "/ssh/id_rsa" ]; then
    cp /ssh/id_rsa /root/.ssh/id_rsa
    chown -R root:root /root/.ssh/id_rsa
    chmod 600 /root/.ssh/id_rsa

    cp /ssh/id_rsa /var/www/.ssh/id_rsa
    chown -R www-data:www-data /var/www/.ssh/id_rsa
    chmod 600 /var/www/.ssh/id_rsa
fi

if [ -e "/gnupg/gpg-key.asc" ]; then
    sudo -u www-data gpg --import /gnupg/gpg-key.asc
fi
if [ -e "/gnupg/gpg-secret-key.asc" ]; then
    sudo -u www-data gpg --import /gnupg/gpg-secret-key.asc
fi
if [ -e "/gnupg/trust.txt" ]; then
    sudo -u www-data gpg --import-ownertrust /gnupg/trust.txt
fi
