FROM fduarte42/docker-php:7.2

# add oci packages
RUN mkdir -p /opt/oracle
COPY driver/oracle/* /tmp/

COPY add-oci.sh /add-oci.sh
RUN bash /add-oci.sh && rm /add-oci.sh

# cleanup
RUN rm -rf /var/lib/apt/lists/*
